Alien Ramen: AARPlayerStateBase Class Reference
AARPlayerStateBase Class Reference
PlayerState backbone for Alien Ramen.
#include <AlienRamen/Public/ARPlayerStateBase.h>
Inherits APlayerState, IAbilitySystemInterface, and IStructSerializable.
Public Member Functions
FARPlayerCoreAttributeSnapshot GetCoreAttributeSnapshot () const
Snapshot of core attributes for UI polling on remote/local players.
float GetCoreAttributeValue (EARCoreAttributeType AttributeType) const
Returns the current value of a core attribute (health/spice/move speed).
float GetSpiceNormalized () const
Normalized spice meter (0..1) derived from GAS attributes.
void SetCharacterPicked (EARCharacterChoice NewCharacter)
Sets picked character; client calls route to server.
void SetPlayerSlot (EARPlayerSlot NewSlot)
Sets the authoritative player slot (P1/P2).
Detailed Description
PlayerState backbone for Alien Ramen.
Owns the authoritative ASC + shared attribute set.
Replicates identity (slot, display name, picked character) and lobby readiness.
Carries loadout tags that drive ability/equipment initialization.
Implements IStructSerializable for save/load handoff across travel.
Definition at line 162 of file ARPlayerStateBase.h.
Member Function Documentation
GetCoreAttributeSnapshot()
FARPlayerCoreAttributeSnapshot AARPlayerStateBase::GetCoreAttributeSnapshot () const
Snapshot of core attributes for UI polling on remote/local players.
Definition at line 81 of file ARPlayerStateBase.cpp.
References GetCoreAttributeValue().
GetCoreAttributeValue()
float AARPlayerStateBase::GetCoreAttributeValue (EARCoreAttributeType AttributeType) const
Returns the current value of a core attribute (health/spice/move speed).
Definition at line 57 of file ARPlayerStateBase.cpp.
Referenced by GetCoreAttributeSnapshot(), and GetSpiceNormalized().
GetSpiceNormalized()
float AARPlayerStateBase::GetSpiceNormalized () const
Normalized spice meter (0..1) derived from GAS attributes.
Definition at line 92 of file ARPlayerStateBase.cpp.
References GetCoreAttributeValue().
SetCharacterPicked()
void AARPlayerStateBase::SetCharacterPicked (EARCharacterChoice NewCharacter)
Sets picked character; client calls route to server.
Definition at line 128 of file ARPlayerStateBase.cpp.
SetPlayerSlot()
void AARPlayerStateBase::SetPlayerSlot (EARPlayerSlot NewSlot)
Sets the authoritative player slot (P1/P2).
Server only.
Definition at line 114 of file ARPlayerStateBase.cpp.
The documentation for this class was generated from the following files:
ARPlayerStateBase.h
ARPlayerStateBase.cpp