Alien Ramen: AARPlayerController Class Reference
AARPlayerController Class Reference
Base player controller: owns save sync RPCs, travel requests, and common ability set handoff.
#include <AlienRamen/Public/ARPlayerController.h>
Inherits APlayerController.
Inherited by AARInvaderPlayerController, AARLobbyPlayerController, AARScrapyardPlayerController, and AARShopPlayerController.
Public Member Functions
void BP_OnPauseMenuClosed ()
BP hook fired when this controller exits local pause-menu state.
void BP_OnPauseMenuOpened (bool bShouldDisplayOverlay)
BP hook fired when this controller enters local pause-menu state.
void ClosePause ()
Alias for RequestClosePauseMenu for UI/input bindings.
bool IsPauseMenuBlockedLocal () const
Returns true when this local controller cannot open pause menu due to policy/system blockers.
bool IsPauseMenuOpenLocal () const
Returns true if this local controller currently has pause-menu state active.
bool IsPauseMenuOverlayVisibleLocal () const
Returns true if this local controller should currently display pause overlay content.
void RequestClosePauseMenu ()
Closes pause menu for all local AR controllers on this machine (C++ path).
void RequestOpenPauseMenu ()
Opens pause menu for all local AR controllers on this machine (if not blocked).
void RequestTogglePauseMenu ()
Toggles pause menu for all local AR controllers on this machine.
void ServerSetPauseMenuVote (bool bPaused)
Server mutation endpoint for this controller's pause-menu vote.
void SetPauseMenuBlocked (bool bBlocked, FName Reason=NAME_None)
Adds/removes local pause blocker reason (terminal/menu/etc).
Public Attributes
FAROnPauseMenuOverlayVisibilityChangedSignature OnPauseMenuOverlayVisibilityChanged
Broadcast when this controller should show/hide pause overlay content.
FAROnPauseMenuStateChangedSignature OnPauseMenuStateChanged
Broadcast when this controller's local pause-menu state flips.
Protected Attributes
bool bAutoApplyDefaultInputMappings = true
Automatically applies/removes DefaultInputMappings for local controllers at lifecycle boundaries.
bool bAutoManagePauseInputContexts = true
Automatically swaps Enhanced Input mapping contexts when pause menu opens/closes.
bool bAutoManagePauseInputMode = true
Automatically switches controller input mode and cursor visibility when paused.
TArray< FARControllerInputMapping > DefaultInputMappings
Base gameplay mappings for this controller; pause flow removes/restores these automatically.
TObjectPtr< UInputMappingContext > PauseMenuInputMappingContext = nullptr
Pause menu mapping context applied while pause menu is open.
int32 PauseMenuInputPriority = 1000
Priority used when adding PauseMenuInputMappingContext.
TSubclassOf< UUserWidget > PauseOverlayWidgetClass
Overlay widget class shown while pause menu is open on overlay-owning local controllers.
int32 PauseOverlayWidgetZOrder = 2000
Viewport z-order for PauseOverlayWidgetClass instances.
Detailed Description
Base player controller: owns save sync RPCs, travel requests, and common ability set handoff.
Definition at line 43 of file ARPlayerController.h.
Member Function Documentation
BP_OnPauseMenuClosed()
void AARPlayerController::BP_OnPauseMenuClosed ()
BP hook fired when this controller exits local pause-menu state.
BP_OnPauseMenuOpened()
void AARPlayerController::BP_OnPauseMenuOpened (bool bShouldDisplayOverlay)
BP hook fired when this controller enters local pause-menu state.
ClosePause()
void AARPlayerController::ClosePause ()
Alias for RequestClosePauseMenu for UI/input bindings.
Definition at line 507 of file ARPlayerController.cpp.
References RequestClosePauseMenu().
IsPauseMenuBlockedLocal()
bool AARPlayerController::IsPauseMenuBlockedLocal () const
Returns true when this local controller cannot open pause menu due to policy/system blockers.
Definition at line 554 of file ARPlayerController.cpp.
Referenced by RequestOpenPauseMenu().
IsPauseMenuOpenLocal()
bool AARPlayerController::IsPauseMenuOpenLocal () const inline
Returns true if this local controller currently has pause-menu state active.
Definition at line 160 of file ARPlayerController.h.
Referenced by RequestTogglePauseMenu().
IsPauseMenuOverlayVisibleLocal()
bool AARPlayerController::IsPauseMenuOverlayVisibleLocal () const inline
Returns true if this local controller should currently display pause overlay content.
Definition at line 164 of file ARPlayerController.h.
RequestClosePauseMenu()
void AARPlayerController::RequestClosePauseMenu ()
Closes pause menu for all local AR controllers on this machine (C++ path).
Definition at line 483 of file ARPlayerController.cpp.
Referenced by ClosePause(), RequestTogglePauseMenu(), and SetPauseMenuBlocked().
RequestOpenPauseMenu()
void AARPlayerController::RequestOpenPauseMenu ()
Opens pause menu for all local AR controllers on this machine (if not blocked).
Definition at line 441 of file ARPlayerController.cpp.
References IsPauseMenuBlockedLocal().
Referenced by RequestTogglePauseMenu().
RequestTogglePauseMenu()
void AARPlayerController::RequestTogglePauseMenu ()
Toggles pause menu for all local AR controllers on this machine.
Definition at line 512 of file ARPlayerController.cpp.
References IsPauseMenuOpenLocal(), RequestClosePauseMenu(), and RequestOpenPauseMenu().
ServerSetPauseMenuVote()
void AARPlayerController::ServerSetPauseMenuVote (bool bPaused)
Server mutation endpoint for this controller's pause-menu vote.
SetPauseMenuBlocked()
void AARPlayerController::SetPauseMenuBlocked (bool bBlocked, FName Reason = NAME_None)
Adds/removes local pause blocker reason (terminal/menu/etc).
Definition at line 569 of file ARPlayerController.cpp.
References RequestClosePauseMenu().
Member Data Documentation
bAutoApplyDefaultInputMappings
bool AARPlayerController::bAutoApplyDefaultInputMappings = true protected
Automatically applies/removes DefaultInputMappings for local controllers at lifecycle boundaries.
Definition at line 201 of file ARPlayerController.h.
bAutoManagePauseInputContexts
bool AARPlayerController::bAutoManagePauseInputContexts = true protected
Automatically swaps Enhanced Input mapping contexts when pause menu opens/closes.
Definition at line 221 of file ARPlayerController.h.
bAutoManagePauseInputMode
bool AARPlayerController::bAutoManagePauseInputMode = true protected
Automatically switches controller input mode and cursor visibility when paused.
Definition at line 241 of file ARPlayerController.h.
DefaultInputMappings
TArray<FARControllerInputMapping> AARPlayerController::DefaultInputMappings protected
Base gameplay mappings for this controller; pause flow removes/restores these automatically.
Definition at line 205 of file ARPlayerController.h.
OnPauseMenuOverlayVisibilityChanged
FAROnPauseMenuOverlayVisibilityChangedSignature AARPlayerController::OnPauseMenuOverlayVisibilityChanged
Broadcast when this controller should show/hide pause overlay content.
Definition at line 184 of file ARPlayerController.h.
OnPauseMenuStateChanged
FAROnPauseMenuStateChangedSignature AARPlayerController::OnPauseMenuStateChanged
Broadcast when this controller's local pause-menu state flips.
Definition at line 180 of file ARPlayerController.h.
PauseMenuInputMappingContext
TObjectPtr<UInputMappingContext> AARPlayerController::PauseMenuInputMappingContext = nullptr protected
Pause menu mapping context applied while pause menu is open.
Definition at line 225 of file ARPlayerController.h.
PauseMenuInputPriority
int32 AARPlayerController::PauseMenuInputPriority = 1000 protected
Priority used when adding PauseMenuInputMappingContext.
Definition at line 229 of file ARPlayerController.h.
PauseOverlayWidgetClass
TSubclassOf<UUserWidget> AARPlayerController::PauseOverlayWidgetClass protected
Overlay widget class shown while pause menu is open on overlay-owning local controllers.
Definition at line 233 of file ARPlayerController.h.
PauseOverlayWidgetZOrder
int32 AARPlayerController::PauseOverlayWidgetZOrder = 2000 protected
Viewport z-order for PauseOverlayWidgetClass instances.
Definition at line 237 of file ARPlayerController.h.
The documentation for this class was generated from the following files:
ARPlayerController.h
ARPlayerController.cpp