Alien Ramen: AARPlayerCharacterInvader Class Reference
AARPlayerCharacterInvader Class Reference
Base ship character for Alien Ramen.
#include <AlienRamen/Public/ARPlayerCharacterInvader.h>
Public Member Functions
bool ActivateAbilityByTag (FGameplayTag Tag, bool bAllowRemoteActivation=true)
Activates ONE ability that matches this tag (deterministic pick).
bool ActivateAbilityByTags (const FGameplayTagContainer &InTagsToActivate, bool bAllowRemoteActivation=true)
Activates ONE ability that matches ANY of the tags (deterministic pick).
int32 ActivateAllAbilitiesByTag (FGameplayTag Tag, bool bAllowRemoteActivation=true)
Activates ALL abilities matching this tag (optional use-case).
void CancelAbilityByTag (FGameplayTag Tag)
Cancels abilities that match this tag (tag must be on the ability).
void CancelAbilityByTags (const FGameplayTagContainer &InTagsToCancel)
Cancels abilities that match ANY of the tags (tags must be on the ability).
void ServerRequestCollectInvaderDrop (AARInvaderDropBase *Drop)
Client request path for pickup collection; server validates range and collection state.
Detailed Description
Base ship character for Alien Ramen.
ASC is owned by PlayerState, Avatar is this pawn.
On server possession: clears loadout, grants common ability set, then resolves ship/hat rows from LoadoutTags and applies baseline. Secondary lane is legacy/deprecated and optional.
Exposes generic tag-based activation/cancel API for PlayerController / Blueprint.
Definition at line 42 of file ARPlayerCharacterInvader.h.
Member Function Documentation
ActivateAbilityByTag()
bool AARPlayerCharacterInvader::ActivateAbilityByTag (FGameplayTag Tag, bool bAllowRemoteActivation = true)
Activates ONE ability that matches this tag (deterministic pick).
Definition at line 1233 of file ARPlayerCharacterInvader.cpp.
References ActivateAbilityByTags().
ActivateAbilityByTags()
bool AARPlayerCharacterInvader::ActivateAbilityByTags (const FGameplayTagContainer & InTagsToActivate, bool bAllowRemoteActivation = true)
Activates ONE ability that matches ANY of the tags (deterministic pick).
Definition at line 1243 of file ARPlayerCharacterInvader.cpp.
Referenced by ActivateAbilityByTag().
ActivateAllAbilitiesByTag()
int32 AARPlayerCharacterInvader::ActivateAllAbilitiesByTag (FGameplayTag Tag, bool bAllowRemoteActivation = true)
Activates ALL abilities matching this tag (optional use-case).
Definition at line 1267 of file ARPlayerCharacterInvader.cpp.
CancelAbilityByTag()
void AARPlayerCharacterInvader::CancelAbilityByTag (FGameplayTag Tag)
Cancels abilities that match this tag (tag must be on the ability).
Definition at line 1296 of file ARPlayerCharacterInvader.cpp.
References CancelAbilityByTags().
CancelAbilityByTags()
void AARPlayerCharacterInvader::CancelAbilityByTags (const FGameplayTagContainer & InTagsToCancel)
Cancels abilities that match ANY of the tags (tags must be on the ability).
Definition at line 1306 of file ARPlayerCharacterInvader.cpp.
Referenced by CancelAbilityByTag().
ServerRequestCollectInvaderDrop()
void AARPlayerCharacterInvader::ServerRequestCollectInvaderDrop (AARInvaderDropBase * Drop)
Client request path for pickup collection; server validates range and collection state.
The documentation for this class was generated from the following files:
ARPlayerCharacterInvader.h
ARPlayerCharacterInvader.cpp